### ISSUE TITLE
Problems with 1.5.1 and 1.5.1.1.

### ISSUE THREAD

**Issue by mafede** [danielwelch/hassio-zigbee2mqtt#199]
Since the update to version 1.5.1 and with the new update to 1.5.1.1, I see that the graphs of the temperature, humidity and atmospheric pressure sensors are not shown.

I also have the feeling that the status update in both the aqara temperature sensors and the aqara of movement, is slower and dilates more in time than with the previous version.

This is my configuration for configuration.yaml of zigbee2mqtt

{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.1.200:1883",
    "user": "DVES_USER",
    "password": "DVES_PASS"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}

Thank's

**Comment by mafede** [comment]
The graphics issue, I have already fixed it. I have seen that it was not just a problem of the zigbee2mqtt devices, and that they were of all the devices, searching the internet I have seen that deleting the database (home-assistant_v2.db) was fixed, and so it has been.

**Comment by GJ2019** [comment]
@mafade; but do you get status updates trom your devices now? Mine are still having a issue

**Comment by mafede** [comment]
@GJ2019 Yes, after re-linking them one by one, I receive updates. I think, or that is my feeling, that it does not update as fast as before and that there are now devices that spend more time without updating. But it is a sensation anyway.

How often does it update you?

For example the aqara motion sensors and the aqara temperature sensors. I can be 15 minutes without updating.

**Comment by GJ2019** [comment]
@mafade: As far as i understand the working process of the sensors is that they only send a update to the system when a change is registered. So if the temperature changes every minute , it will send a update every minute. Is there no significant change , it won’t send updates that often. Since the temperature sensors also measure humidity and pressure, it will update more often.

**Comment by mafede** [comment]
@GJ2019 You are right, it is logical. That's why I said about "my feeling" the same now after the update and the problems I've noticed more and it's really not serious.

**Comment by danielwelch** [comment]
Looks like you solved this, so I'll close the issue.
