### ISSUE TITLE
Secret network_key

### ISSUE THREAD

**Issue by Erelen-Laiquendi** [danielwelch/hassio-zigbee2mqtt#259]
**zigbee2mqtt add-on version:** 1.7.0
**Operating environment:** HassOS

**Description of problem:**
According https://www.zigbee2mqtt.io/information/configuration.html, in addon, I can use `user: '!secret user'` and `password: '!secret password'`, but I can't use `network_key: '!secret network_key'` - "not a valid value for dictionary value".

**Comment by danielwelch** [comment]
If this isn't something simple (like forgetting to put `network_key` in your secrets file), I'd guess it's related to how hassio deals with mapping in nested values from secrets. I haven't looked at the code around that so I'm only guessing at this point.

**Comment by CodeFinder2** [comment]
I can confirm this issue. Would be great if this would be possible. 🙈

**Comment by danielwelch** [comment]
Here’s the issue:

https://github.com/home-assistant/hassio/blob/a3c3f1580637e1cf90570746ca2406aae3244b80/hassio/secrets.py#L56

Hass.io filters out all types other than those listed below. So essentially, lists are not supported in the secrets file.

**Comment by CodeFinder2** [comment]
This is still relevant, isn't it? 🙈

**Comment by danielwelch** [comment]
@CodeFinder2 Yep, it would be nice, but won't be fixed until it's fixed in Hass.io. I submitted a PR, they understandably wanted tests. I was hoping to add a simple test case but as far as I could tell, most/all of the add-on configuration validation is untested. I didn't have time to write tests for the whole validation system, maybe some day.

**Comment by Erelen-Laiquendi** [comment]
#283, #263 - thanks, @felixstorm!

**Comment by litris** [comment]
The problem still persists User and Password work correctly with secrets.yalm but network_key: '! Secret network_key' does not work when clicking on "Save" gives an error.

Any solution?

**Comment by Erelen-Laiquendi** [comment]
Addon configuration:
```
advanced:
  network_key: []
  network_key_string: '!secret addon_zigbee2mqtt_network_key'
```

secrets.yaml:
```
addon_zigbee2mqtt_network_key: "000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000"
```
(with your real key in this format)

**Comment by litris** [comment]
> Addon configuration:
> 
> ```
> advanced:
>   network_key: []
>   network_key_string: '!secret addon_zigbee2mqtt_network_key'
> ```
> 
> secrets.yaml:
> 
> ```
> addon_zigbee2mqtt_network_key: "000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000, 000"
> ```
> 
> (with your real key in this format)

Ok it works!

Thanks.
